name: ci-wf
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Linting jobs
        run: echo "Starting Linting of HTML and CSS files"
      - name: Clone repo on runner
        uses: actions/checkout@v6
      - name: Install Dev Dependencies
        run: npm install
      - name: Lint html files
        run: npx htmlhint "**/*.html"
      - name: Lint css files
        run: npx stylelint "**/*.css"
    
  build-job:
    runs-on: ubuntu-latest
    needs: "linting-job"
    steps:
      - name: Build job
        run: echo "Build Job going to start"
      - name: clone repo
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm install
      - name: build web with parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./" --no-cache
